namespace PatriotIndex.Domain.Frontend;

/// <summary>
/// Derived situational efficiency metrics from <c>SeasonEfficiencyStats</c>. Team-level only.
/// </summary>
public sealed record EfficiencyStatsResult
{
    /// <summary>Thirddown.Successes / Thirddown.Attempts × 100. NFL's most predictive possession efficiency stat. ~42% is league average.</summary>
    public double ThirdDownConvPct { get; init; }

    /// <summary>Fourthdown.Successes / Fourthdown.Attempts × 100. Also reveals analytics-driven coaching aggressiveness.</summary>
    public double FourthDownConvPct { get; init; }

    /// <summary>Redzone.Successes / Redzone.Attempts × 100. Scores (TD or FG) per red zone trip.</summary>
    public double RedzoneConvPct { get; init; }

    /// <summary>Goaltogo.Successes / Goaltogo.Attempts × 100. TD rate with the ball inside the 10. Separates teams that score TDs from those settling for FGs.</summary>
    public double GoalToGoConvPct { get; init; }

    /// <summary>3rd-down attempts raw count.</summary>
    public int ThirdDownAttempts { get; init; }

    /// <summary>4th-down attempts raw count. Higher count = more aggressive coaching philosophy.</summary>
    public int FourthDownAttempts { get; init; }

    /// <summary>Red zone trips raw count.</summary>
    public int RedzoneAttempts { get; init; }

    /// <summary>Goal-to-go situations raw count.</summary>
    public int GoalToGoAttempts { get; init; }
}

/// <summary>
/// Derived first-down distribution metrics from <c>SeasonFirstDownStats</c>. Team-level only.
/// </summary>
public sealed record FirstDownStatsResult
{
    /// <summary>Pass / Total × 100. Proportion of first downs earned through the passing game.</summary>
    public double PassFirstDownPct { get; init; }

    /// <summary>Rush / Total × 100. Proportion earned through the running game.</summary>
    public double RushFirstDownPct { get; init; }

    /// <summary>Penalty / Total × 100. First downs via opponent penalties; high % may indicate chip-based offensive strategy.</summary>
    public double PenaltyFirstDownPct { get; init; }

    /// <summary>Total first downs raw count.</summary>
    public int Total { get; init; }
}

/// <summary>
/// Derived touchdown-source metrics from <c>SeasonTouchdownStats</c>. Team-level only.
/// </summary>
public sealed record TouchdownDistributionResult
{
    /// <summary>Pass / Total × 100. Offensive passing TD share.</summary>
    public double PassTdPct { get; init; }

    /// <summary>Rush / Total × 100. Offensive rushing TD share.</summary>
    public double RushTdPct { get; init; }

    /// <summary>TotalReturn / Total × 100. Combined return TD share (kick + punt + misc).</summary>
    public double ReturnTdPct { get; init; }

    /// <summary>(FumbleReturn + IntReturn) / Total × 100. TDs generated by the defense itself.</summary>
    public double DefensiveTdPct { get; init; }

    /// <summary>KickReturn / Total × 100.</summary>
    public double KickReturnTdPct { get; init; }

    /// <summary>PuntReturn / Total × 100.</summary>
    public double PuntReturnTdPct { get; init; }

    /// <summary>Total touchdowns raw count.</summary>
    public int Total { get; init; }
}

/// <summary>
/// Derived team-level interception metrics from <c>SeasonInterceptionStats</c>.
/// </summary>
public sealed record TeamInterceptionStatsResult
{
    /// <summary>Returned / Interceptions × 100. How often the team runs back rather than kneeling after a pick.</summary>
    public double ReturnRate { get; init; }

    /// <summary>ReturnYards / Returned. Average field-position gain per returned interception.</summary>
    public double AverageReturnYards { get; init; }

    /// <summary>Total interceptions raw count.</summary>
    public int Interceptions { get; init; }
}

/// <summary>
/// Team-level turnover picture combining offense and defense data.
/// Populated by <c>TeamStatsService</c> using multiple stat blocks.
/// </summary>
public sealed record TurnoverDifferentialResult
{
    /// <summary>Defense.Interceptions + Defense.FumbleRecoveries. Total takeaways.</summary>
    public int Takeaways { get; init; }

    /// <summary>Passing.Interceptions + Fumbles.LostFumbles. Total giveaways.</summary>
    public int Giveaways { get; init; }

    /// <summary>Takeaways − Giveaways. Net turnover margin; among top-5 predictors of win percentage in the NFL.</summary>
    public int Differential { get; init; }
}
