// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PatriotIndex.Domain;

#nullable disable

namespace PatriotIndex.Domain.Migrations
{
    [DbContext(typeof(PatriotIndexDbContext))]
    [Migration("20260224190542_UpdatedPlayer")]
    partial class UpdatedPlayer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_coaches");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_coaches_team_id");

                    b.ToTable("coaches", (string)null);
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.CoinToss", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("decision");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<Guid>("PeriodId1")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id1");

                    b.Property<Guid>("WinnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_id");

                    b.HasKey("Id")
                        .HasName("pk_coin_tosses");

                    b.HasIndex("PeriodId")
                        .HasDatabaseName("ix_coin_tosses_period_id");

                    b.HasIndex("PeriodId1")
                        .HasDatabaseName("ix_coin_tosses_period_id1");

                    b.HasIndex("WinnerId")
                        .HasDatabaseName("ix_coin_tosses_winner_id");

                    b.ToTable("coin_tosses", (string)null);
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Conference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_conferences");

                    b.HasIndex("Alias")
                        .IsUnique()
                        .HasDatabaseName("ix_conferences_alias");

                    b.ToTable("conferences", (string)null);
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Division", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<Guid>("ConferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("conference_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_divisions");

                    b.HasIndex("ConferenceId")
                        .HasDatabaseName("ix_divisions_conference_id");

                    b.ToTable("divisions", (string)null);
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Drive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("DefensivePoints")
                        .HasColumnType("integer")
                        .HasColumnName("defensive_points");

                    b.Property<int?>("DefensiveStartPoints")
                        .HasColumnType("integer")
                        .HasColumnName("defensive_start_points");

                    b.Property<Guid>("DefensiveTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("defensive_team_id");

                    b.Property<string>("Duration")
                        .HasColumnType("text")
                        .HasColumnName("duration");

                    b.Property<string>("EndClock")
                        .HasColumnType("text")
                        .HasColumnName("end_clock");

                    b.Property<string>("EndReason")
                        .HasColumnType("text")
                        .HasColumnName("end_reason");

                    b.Property<int?>("FarthestDriveYardLine")
                        .HasColumnType("integer")
                        .HasColumnName("farthest_drive_yard_line");

                    b.Property<int?>("FirstDowns")
                        .HasColumnType("integer")
                        .HasColumnName("first_downs");

                    b.Property<int?>("FirstDriveYardLine")
                        .HasColumnType("integer")
                        .HasColumnName("first_drive_yard_line");

                    b.Property<int?>("GainedYards")
                        .HasColumnType("integer")
                        .HasColumnName("gained_yards");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<int?>("LastDriveYardLine")
                        .HasColumnType("integer")
                        .HasColumnName("last_drive_yard_line");

                    b.Property<int?>("NetYards")
                        .HasColumnType("integer")
                        .HasColumnName("net_yards");

                    b.Property<int?>("OffensivePoints")
                        .HasColumnType("integer")
                        .HasColumnName("offensive_points");

                    b.Property<int?>("OffensiveStartPoints")
                        .HasColumnType("integer")
                        .HasColumnName("offensive_start_points");

                    b.Property<Guid>("OffensiveTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("offensive_team_id");

                    b.Property<int?>("PatPointsAttempted")
                        .HasColumnType("integer")
                        .HasColumnName("pat_points_attempted");

                    b.Property<int?>("PenaltyYards")
                        .HasColumnType("integer")
                        .HasColumnName("penalty_yards");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<Guid?>("PeriodId1")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id1");

                    b.Property<int?>("PeriodNumber")
                        .HasColumnType("integer")
                        .HasColumnName("period_number");

                    b.Property<int?>("PlayCount")
                        .HasColumnType("integer")
                        .HasColumnName("play_count");

                    b.Property<int?>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("StartClock")
                        .HasColumnType("text")
                        .HasColumnName("start_clock");

                    b.Property<string>("StartReason")
                        .HasColumnType("text")
                        .HasColumnName("start_reason");

                    b.Property<int?>("TeamSequence")
                        .HasColumnType("integer")
                        .HasColumnName("team_sequence");

                    b.HasKey("Id")
                        .HasName("pk_drives");

                    b.HasIndex("DefensiveTeamId")
                        .HasDatabaseName("ix_drives_defensive_team_id");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_drives_game_id");

                    b.HasIndex("OffensiveTeamId")
                        .HasDatabaseName("ix_drives_offensive_team_id");

                    b.HasIndex("PeriodId1")
                        .HasDatabaseName("ix_drives_period_id1");

                    b.HasIndex("PeriodId", "Sequence")
                        .HasDatabaseName("ix_drives_period_id_sequence");

                    b.ToTable("drives", (string)null);
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.DriveEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer")
                        .HasColumnName("away_score");

                    b.Property<bool>("Blitz")
                        .HasColumnType("boolean")
                        .HasColumnName("blitz");

                    b.Property<string>("Clock")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clock");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DriveId")
                        .HasColumnType("uuid")
                        .HasColumnName("drive_id");

                    b.Property<int>("DriveType")
                        .HasColumnType("integer")
                        .HasColumnName("drive_type");

                    b.Property<string>("EndClock")
                        .HasColumnType("text")
                        .HasColumnName("end_clock");

                    b.Property<int>("EndDown")
                        .HasColumnType("integer")
                        .HasColumnName("end_down");

                    b.Property<int>("EndLocationYardLine")
                        .HasColumnType("integer")
                        .HasColumnName("end_location_yard_line");

                    b.Property<Guid>("EndPossessionTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("end_possession_team_id");

                    b.Property<Guid?>("EndTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("end_team_id");

                    b.Property<int>("EndYardsToGain")
                        .HasColumnType("integer")
                        .HasColumnName("end_yards_to_gain");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<bool>("FakeFieldGoal")
                        .HasColumnType("boolean")
                        .HasColumnName("fake_field_goal");

                    b.Property<bool>("FakePunt")
                        .HasColumnType("boolean")
                        .HasColumnName("fake_punt");

                    b.Property<string>("HashMark")
                        .HasColumnType("text")
                        .HasColumnName("hash_mark");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer")
                        .HasColumnName("home_score");

                    b.Property<string>("Huddle")
                        .HasColumnType("text")
                        .HasColumnName("huddle");

                    b.Property<int?>("LeftTightEnds")
                        .HasColumnType("integer")
                        .HasColumnName("left_tight_ends");

                    b.Property<int?>("MenInBox")
                        .HasColumnType("integer")
                        .HasColumnName("men_in_box");

                    b.Property<string>("PassRoute")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pass_route");

                    b.Property<bool>("PlayAction")
                        .HasColumnType("boolean")
                        .HasColumnName("play_action");

                    b.Property<string>("PlayDirection")
                        .HasColumnType("text")
                        .HasColumnName("play_direction");

                    b.Property<string>("PlayType")
                        .HasColumnType("text")
                        .HasColumnName("play_type");

                    b.Property<int?>("PlayersRushed")
                        .HasColumnType("integer")
                        .HasColumnName("players_rushed");

                    b.Property<string>("PocketLocation")
                        .HasColumnType("text")
                        .HasColumnName("pocket_location");

                    b.Property<string>("QbSnap")
                        .HasColumnType("text")
                        .HasColumnName("qb_snap");

                    b.Property<int?>("RightTightEnds")
                        .HasColumnType("integer")
                        .HasColumnName("right_tight_ends");

                    b.Property<bool>("RunPassOption")
                        .HasColumnType("boolean")
                        .HasColumnName("run_pass_option");

                    b.Property<bool>("ScreenPass")
                        .HasColumnType("boolean")
                        .HasColumnName("screen_pass");

                    b.Property<decimal>("Sequence")
                        .HasColumnType("numeric")
                        .HasColumnName("sequence");

                    b.Property<string>("StartClock")
                        .HasColumnType("text")
                        .HasColumnName("start_clock");

                    b.Property<int>("StartDown")
                        .HasColumnType("integer")
                        .HasColumnName("start_down");

                    b.Property<int>("StartLocationYardLine")
                        .HasColumnType("integer")
                        .HasColumnName("start_location_yard_line");

                    b.Property<Guid>("StartPossessionTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("start_possession_team_id");

                    b.Property<Guid?>("StartTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("start_team_id");

                    b.Property<int>("StartYardsToGain")
                        .HasColumnType("integer")
                        .HasColumnName("start_yards_to_gain");

                    b.Property<string>("WallClock")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("wall_clock");

                    b.HasKey("Id")
                        .HasName("pk_pbp_drive_events");

                    b.HasIndex("DriveId")
                        .HasDatabaseName("ix_pbp_drive_events_drive_id");

                    b.HasIndex("EndPossessionTeamId")
                        .HasDatabaseName("ix_pbp_drive_events_end_possession_team_id");

                    b.HasIndex("EndTeamId")
                        .HasDatabaseName("ix_pbp_drive_events_end_team_id");

                    b.HasIndex("Sequence")
                        .HasDatabaseName("ix_pbp_drive_events_sequence");

                    b.HasIndex("StartPossessionTeamId")
                        .HasDatabaseName("ix_pbp_drive_events_start_possession_team_id");

                    b.HasIndex("StartTeamId")
                        .HasDatabaseName("ix_pbp_drive_events_start_team_id");

                    b.ToTable("pbp_drive_events", (string)null);
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Attendance")
                        .HasColumnType("integer")
                        .HasColumnName("attendance");

                    b.Property<int?>("AwayPoints")
                        .HasColumnType("integer")
                        .HasColumnName("away_points");

                    b.Property<Guid?>("AwayTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("away_team_id");

                    b.Property<string>("BroadcastNetwork")
                        .HasColumnType("text")
                        .HasColumnName("broadcast_network");

                    b.Property<bool>("ConferenceGame")
                        .HasColumnType("boolean")
                        .HasColumnName("conference_game");

                    b.Property<string>("Duration")
                        .HasColumnType("text")
                        .HasColumnName("duration");

                    b.Property<string>("GameType")
                        .HasColumnType("text")
                        .HasColumnName("game_type");

                    b.Property<int?>("HomePoints")
                        .HasColumnType("integer")
                        .HasColumnName("home_points");

                    b.Property<Guid?>("HomeTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_team_id");

                    b.Property<bool>("NeutralSite")
                        .HasColumnType("boolean")
                        .HasColumnName("neutral_site");

                    b.Property<DateTime?>("Scheduled")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled");

                    b.Property<string>("SeasonType")
                        .HasColumnType("text")
                        .HasColumnName("season_type");

                    b.Property<int?>("SeasonYear")
                        .HasColumnType("integer")
                        .HasColumnName("season_year");

                    b.Property<string>("SrId")
                        .HasColumnType("text")
                        .HasColumnName("sr_id");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.Property<string>("WeatherCondition")
                        .HasColumnType("text")
                        .HasColumnName("weather_condition");

                    b.Property<int?>("WeatherHumidity")
                        .HasColumnType("integer")
                        .HasColumnName("weather_humidity");

                    b.Property<int?>("WeatherTemp")
                        .HasColumnType("integer")
                        .HasColumnName("weather_temp");

                    b.Property<string>("WeatherWindDirection")
                        .HasColumnType("text")
                        .HasColumnName("weather_wind_direction");

                    b.Property<int?>("WeatherWindSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("weather_wind_speed");

                    b.Property<int?>("WeekSequence")
                        .HasColumnType("integer")
                        .HasColumnName("week_sequence");

                    b.Property<string>("WeekTitle")
                        .HasColumnType("text")
                        .HasColumnName("week_title");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("AwayTeamId")
                        .HasDatabaseName("ix_games_away_team_id");

                    b.HasIndex("HomeTeamId")
                        .HasDatabaseName("ix_games_home_team_id");

                    b.HasIndex("Scheduled")
                        .HasDatabaseName("ix_games_scheduled");

                    b.HasIndex("SrId")
                        .IsUnique()
                        .HasDatabaseName("ix_games_sr_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_games_venue_id");

                    b.HasIndex("SeasonYear", "SeasonType", "WeekSequence")
                        .HasDatabaseName("ix_games_season_year_season_type_week_sequence");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.PbpEventStatistics", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("StatType")
                        .HasColumnType("text")
                        .HasColumnName("stat_type");

                    b.Property<int?>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int?>("Complete")
                        .HasColumnType("integer")
                        .HasColumnName("complete");

                    b.Property<Guid?>("DriveEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("drive_event_id");

                    b.Property<JsonDocument>("ExtraData")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra_data");

                    b.Property<int?>("FirstDown")
                        .HasColumnType("integer")
                        .HasColumnName("first_down");

                    b.Property<int?>("Fumble")
                        .HasColumnType("integer")
                        .HasColumnName("fumble");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int?>("Interception")
                        .HasColumnType("integer")
                        .HasColumnName("interception");

                    b.Property<int?>("Penalty")
                        .HasColumnType("integer")
                        .HasColumnName("penalty");

                    b.Property<int?>("PenaltyYards")
                        .HasColumnType("integer")
                        .HasColumnName("penalty_yards");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int?>("ReturnYards")
                        .HasColumnType("integer")
                        .HasColumnName("return_yards");

                    b.Property<int?>("Sack")
                        .HasColumnType("integer")
                        .HasColumnName("sack");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<int?>("Touchback")
                        .HasColumnType("integer")
                        .HasColumnName("touchback");

                    b.Property<int?>("Touchdown")
                        .HasColumnType("integer")
                        .HasColumnName("touchdown");

                    b.Property<int?>("Yards")
                        .HasColumnType("integer")
                        .HasColumnName("yards");

                    b.HasKey("EventId", "StatType")
                        .HasName("pk_pbp_event_statistics");

                    b.HasIndex("DriveEventId")
                        .HasDatabaseName("ix_pbp_event_statistics_drive_event_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_pbp_event_statistics_player_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_pbp_event_statistics_team_id");

                    b.ToTable("pbp_event_statistics", (string)null);
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Period", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer")
                        .HasColumnName("away_score");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid?>("GameId1")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id1");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer")
                        .HasColumnName("home_score");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_periods");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_periods_game_id");

                    b.HasIndex("GameId1")
                        .HasDatabaseName("ix_periods_game_id1");

                    b.HasIndex("GameId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_periods_game_id_number");

                    b.ToTable("periods", (string)null);
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("College")
                        .HasColumnType("text")
                        .HasColumnName("college");

                    b.Property<int?>("DraftPick")
                        .HasColumnType("integer")
                        .HasColumnName("draft_pick");

                    b.Property<int?>("DraftRound")
                        .HasColumnType("integer")
                        .HasColumnName("draft_round");

                    b.Property<Guid?>("DraftTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_team_id");

                    b.Property<int?>("DraftYear")
                        .HasColumnType("integer")
                        .HasColumnName("draft_year");

                    b.Property<int?>("Experience")
                        .HasColumnType("integer")
                        .HasColumnName("experience");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("Jersey")
                        .HasColumnType("text")
                        .HasColumnName("jersey");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int?>("RookieYear")
                        .HasColumnType("integer")
                        .HasColumnName("rookie_year");

                    b.Property<long?>("Salary")
                        .HasColumnType("bigint")
                        .HasColumnName("salary");

                    b.Property<string>("SrId")
                        .HasColumnType("text")
                        .HasColumnName("sr_id");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("DraftTeamId")
                        .HasDatabaseName("ix_players_draft_team_id");

                    b.HasIndex("SrId")
                        .IsUnique()
                        .HasDatabaseName("ix_players_sr_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_players_team_id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.PlayerGameStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DefAssists")
                        .HasColumnType("integer")
                        .HasColumnName("def_assists");

                    b.Property<int>("DefForcedFumbles")
                        .HasColumnType("integer")
                        .HasColumnName("def_forced_fumbles");

                    b.Property<int>("DefInterceptions")
                        .HasColumnType("integer")
                        .HasColumnName("def_interceptions");

                    b.Property<int>("DefPassesDefended")
                        .HasColumnType("integer")
                        .HasColumnName("def_passes_defended");

                    b.Property<int>("DefQbHits")
                        .HasColumnType("integer")
                        .HasColumnName("def_qb_hits");

                    b.Property<double>("DefSacks")
                        .HasColumnType("double precision")
                        .HasColumnName("def_sacks");

                    b.Property<int>("DefTackles")
                        .HasColumnType("integer")
                        .HasColumnName("def_tackles");

                    b.Property<int>("FgAtt")
                        .HasColumnType("integer")
                        .HasColumnName("fg_att");

                    b.Property<int>("FgLong")
                        .HasColumnType("integer")
                        .HasColumnName("fg_long");

                    b.Property<int>("FgMade")
                        .HasColumnType("integer")
                        .HasColumnName("fg_made");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<int>("PassAtt")
                        .HasColumnType("integer")
                        .HasColumnName("pass_att");

                    b.Property<int>("PassCmp")
                        .HasColumnType("integer")
                        .HasColumnName("pass_cmp");

                    b.Property<int>("PassInt")
                        .HasColumnType("integer")
                        .HasColumnName("pass_int");

                    b.Property<double>("PassRating")
                        .HasColumnType("double precision")
                        .HasColumnName("pass_rating");

                    b.Property<int>("PassSackYds")
                        .HasColumnType("integer")
                        .HasColumnName("pass_sack_yds");

                    b.Property<int>("PassSacks")
                        .HasColumnType("integer")
                        .HasColumnName("pass_sacks");

                    b.Property<int>("PassTd")
                        .HasColumnType("integer")
                        .HasColumnName("pass_td");

                    b.Property<int>("PassYds")
                        .HasColumnType("integer")
                        .HasColumnName("pass_yds");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("PuntAtt")
                        .HasColumnType("integer")
                        .HasColumnName("punt_att");

                    b.Property<double>("PuntAvg")
                        .HasColumnType("double precision")
                        .HasColumnName("punt_avg");

                    b.Property<int>("PuntYds")
                        .HasColumnType("integer")
                        .HasColumnName("punt_yds");

                    b.Property<double>("RecAvg")
                        .HasColumnType("double precision")
                        .HasColumnName("rec_avg");

                    b.Property<int>("RecFumbles")
                        .HasColumnType("integer")
                        .HasColumnName("rec_fumbles");

                    b.Property<int>("RecLong")
                        .HasColumnType("integer")
                        .HasColumnName("rec_long");

                    b.Property<int>("RecReceptions")
                        .HasColumnType("integer")
                        .HasColumnName("rec_receptions");

                    b.Property<int>("RecTargets")
                        .HasColumnType("integer")
                        .HasColumnName("rec_targets");

                    b.Property<int>("RecTd")
                        .HasColumnType("integer")
                        .HasColumnName("rec_td");

                    b.Property<int>("RecYds")
                        .HasColumnType("integer")
                        .HasColumnName("rec_yds");

                    b.Property<int>("RushAtt")
                        .HasColumnType("integer")
                        .HasColumnName("rush_att");

                    b.Property<double>("RushAvg")
                        .HasColumnType("double precision")
                        .HasColumnName("rush_avg");

                    b.Property<int>("RushFumbles")
                        .HasColumnType("integer")
                        .HasColumnName("rush_fumbles");

                    b.Property<int>("RushLong")
                        .HasColumnType("integer")
                        .HasColumnName("rush_long");

                    b.Property<int>("RushTd")
                        .HasColumnType("integer")
                        .HasColumnName("rush_td");

                    b.Property<int>("RushYds")
                        .HasColumnType("integer")
                        .HasColumnName("rush_yds");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<int>("XpAtt")
                        .HasColumnType("integer")
                        .HasColumnName("xp_att");

                    b.Property<int>("XpMade")
                        .HasColumnType("integer")
                        .HasColumnName("xp_made");

                    b.HasKey("Id")
                        .HasName("pk_player_game_stats");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_player_game_stats_game_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_player_game_stats_player_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_player_game_stats_team_id");

                    b.HasIndex("PlayerId", "GameId")
                        .IsUnique()
                        .HasDatabaseName("ix_player_game_stats_player_id_game_id");

                    b.ToTable("player_game_stats", (string)null);
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.PlayerSeasonStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DefAssists")
                        .HasColumnType("integer")
                        .HasColumnName("def_assists");

                    b.Property<int>("DefForcedFumbles")
                        .HasColumnType("integer")
                        .HasColumnName("def_forced_fumbles");

                    b.Property<int>("DefInterceptions")
                        .HasColumnType("integer")
                        .HasColumnName("def_interceptions");

                    b.Property<int>("DefPassesDefended")
                        .HasColumnType("integer")
                        .HasColumnName("def_passes_defended");

                    b.Property<int>("DefQbHits")
                        .HasColumnType("integer")
                        .HasColumnName("def_qb_hits");

                    b.Property<double>("DefSacks")
                        .HasColumnType("double precision")
                        .HasColumnName("def_sacks");

                    b.Property<int>("DefTackles")
                        .HasColumnType("integer")
                        .HasColumnName("def_tackles");

                    b.Property<int>("FgAtt")
                        .HasColumnType("integer")
                        .HasColumnName("fg_att");

                    b.Property<int>("FgLong")
                        .HasColumnType("integer")
                        .HasColumnName("fg_long");

                    b.Property<int>("FgMade")
                        .HasColumnType("integer")
                        .HasColumnName("fg_made");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("games_played");

                    b.Property<int>("GamesStarted")
                        .HasColumnType("integer")
                        .HasColumnName("games_started");

                    b.Property<int>("PassAtt")
                        .HasColumnType("integer")
                        .HasColumnName("pass_att");

                    b.Property<int>("PassCmp")
                        .HasColumnType("integer")
                        .HasColumnName("pass_cmp");

                    b.Property<int>("PassInt")
                        .HasColumnType("integer")
                        .HasColumnName("pass_int");

                    b.Property<double>("PassRating")
                        .HasColumnType("double precision")
                        .HasColumnName("pass_rating");

                    b.Property<int>("PassSackYds")
                        .HasColumnType("integer")
                        .HasColumnName("pass_sack_yds");

                    b.Property<int>("PassSacks")
                        .HasColumnType("integer")
                        .HasColumnName("pass_sacks");

                    b.Property<int>("PassTd")
                        .HasColumnType("integer")
                        .HasColumnName("pass_td");

                    b.Property<int>("PassYds")
                        .HasColumnType("integer")
                        .HasColumnName("pass_yds");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("PuntAtt")
                        .HasColumnType("integer")
                        .HasColumnName("punt_att");

                    b.Property<double>("PuntAvg")
                        .HasColumnType("double precision")
                        .HasColumnName("punt_avg");

                    b.Property<int>("PuntYds")
                        .HasColumnType("integer")
                        .HasColumnName("punt_yds");

                    b.Property<double>("RecAvg")
                        .HasColumnType("double precision")
                        .HasColumnName("rec_avg");

                    b.Property<int>("RecFumbles")
                        .HasColumnType("integer")
                        .HasColumnName("rec_fumbles");

                    b.Property<int>("RecLong")
                        .HasColumnType("integer")
                        .HasColumnName("rec_long");

                    b.Property<int>("RecReceptions")
                        .HasColumnType("integer")
                        .HasColumnName("rec_receptions");

                    b.Property<int>("RecTargets")
                        .HasColumnType("integer")
                        .HasColumnName("rec_targets");

                    b.Property<int>("RecTd")
                        .HasColumnType("integer")
                        .HasColumnName("rec_td");

                    b.Property<int>("RecYds")
                        .HasColumnType("integer")
                        .HasColumnName("rec_yds");

                    b.Property<int>("RushAtt")
                        .HasColumnType("integer")
                        .HasColumnName("rush_att");

                    b.Property<double>("RushAvg")
                        .HasColumnType("double precision")
                        .HasColumnName("rush_avg");

                    b.Property<int>("RushFumbles")
                        .HasColumnType("integer")
                        .HasColumnName("rush_fumbles");

                    b.Property<int>("RushLong")
                        .HasColumnType("integer")
                        .HasColumnName("rush_long");

                    b.Property<int>("RushTd")
                        .HasColumnType("integer")
                        .HasColumnName("rush_td");

                    b.Property<int>("RushYds")
                        .HasColumnType("integer")
                        .HasColumnName("rush_yds");

                    b.Property<string>("SeasonType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("season_type");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("integer")
                        .HasColumnName("season_year");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<int>("XpAtt")
                        .HasColumnType("integer")
                        .HasColumnName("xp_att");

                    b.Property<int>("XpMade")
                        .HasColumnType("integer")
                        .HasColumnName("xp_made");

                    b.HasKey("Id")
                        .HasName("pk_player_season_stats");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_player_season_stats_player_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_player_season_stats_team_id");

                    b.HasIndex("PlayerId", "SeasonYear", "SeasonType")
                        .IsUnique()
                        .HasDatabaseName("ix_player_season_stats_player_id_season_year_season_type");

                    b.ToTable("player_season_stats", (string)null);
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.SyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<JsonDocument>("RawResponse")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_response");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sync_logs");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_sync_logs_entity_type");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_sync_logs_started_at");

                    b.ToTable("sync_logs", (string)null);
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<string>("ChampionshipSeasons")
                        .HasColumnType("text")
                        .HasColumnName("championship_seasons");

                    b.Property<int?>("ChampionshipsWon")
                        .HasColumnType("integer")
                        .HasColumnName("championships_won");

                    b.Property<int?>("ConferenceTitles")
                        .HasColumnType("integer")
                        .HasColumnName("conference_titles");

                    b.Property<Guid?>("DivisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("division_id");

                    b.Property<int?>("DivisionTitles")
                        .HasColumnType("integer")
                        .HasColumnName("division_titles");

                    b.Property<short?>("Founded")
                        .HasColumnType("smallint")
                        .HasColumnName("founded");

                    b.Property<string>("GeneralManager")
                        .HasColumnType("text")
                        .HasColumnName("general_manager");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("market");

                    b.Property<string>("Mascot")
                        .HasColumnType("text")
                        .HasColumnName("mascot");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.Property<int?>("PlayoffAppearances")
                        .HasColumnType("integer")
                        .HasColumnName("playoff_appearances");

                    b.Property<string>("President")
                        .HasColumnType("text")
                        .HasColumnName("president");

                    b.Property<string>("SecondaryColor")
                        .HasColumnType("text")
                        .HasColumnName("secondary_color");

                    b.Property<string>("SrId")
                        .HasColumnType("text")
                        .HasColumnName("sr_id");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("Alias")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_alias");

                    b.HasIndex("DivisionId")
                        .HasDatabaseName("ix_teams_division_id");

                    b.HasIndex("SrId")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_sr_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_teams_venue_id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.TeamSeasonStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DefAssists")
                        .HasColumnType("integer")
                        .HasColumnName("def_assists");

                    b.Property<int>("DefForcedFumbles")
                        .HasColumnType("integer")
                        .HasColumnName("def_forced_fumbles");

                    b.Property<int>("DefInterceptions")
                        .HasColumnType("integer")
                        .HasColumnName("def_interceptions");

                    b.Property<int>("DefPassesDefended")
                        .HasColumnType("integer")
                        .HasColumnName("def_passes_defended");

                    b.Property<int>("DefQbHits")
                        .HasColumnType("integer")
                        .HasColumnName("def_qb_hits");

                    b.Property<double>("DefSacks")
                        .HasColumnType("double precision")
                        .HasColumnName("def_sacks");

                    b.Property<int>("DefTackles")
                        .HasColumnType("integer")
                        .HasColumnName("def_tackles");

                    b.Property<int>("FgAtt")
                        .HasColumnType("integer")
                        .HasColumnName("fg_att");

                    b.Property<int>("FgLong")
                        .HasColumnType("integer")
                        .HasColumnName("fg_long");

                    b.Property<int>("FgMade")
                        .HasColumnType("integer")
                        .HasColumnName("fg_made");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("games_played");

                    b.Property<int>("PassAtt")
                        .HasColumnType("integer")
                        .HasColumnName("pass_att");

                    b.Property<int>("PassCmp")
                        .HasColumnType("integer")
                        .HasColumnName("pass_cmp");

                    b.Property<int>("PassInt")
                        .HasColumnType("integer")
                        .HasColumnName("pass_int");

                    b.Property<double>("PassRating")
                        .HasColumnType("double precision")
                        .HasColumnName("pass_rating");

                    b.Property<int>("PassSackYds")
                        .HasColumnType("integer")
                        .HasColumnName("pass_sack_yds");

                    b.Property<int>("PassSacks")
                        .HasColumnType("integer")
                        .HasColumnName("pass_sacks");

                    b.Property<int>("PassTd")
                        .HasColumnType("integer")
                        .HasColumnName("pass_td");

                    b.Property<int>("PassYds")
                        .HasColumnType("integer")
                        .HasColumnName("pass_yds");

                    b.Property<int>("PuntAtt")
                        .HasColumnType("integer")
                        .HasColumnName("punt_att");

                    b.Property<double>("PuntAvg")
                        .HasColumnType("double precision")
                        .HasColumnName("punt_avg");

                    b.Property<int>("PuntYds")
                        .HasColumnType("integer")
                        .HasColumnName("punt_yds");

                    b.Property<double>("RecAvg")
                        .HasColumnType("double precision")
                        .HasColumnName("rec_avg");

                    b.Property<int>("RecFumbles")
                        .HasColumnType("integer")
                        .HasColumnName("rec_fumbles");

                    b.Property<int>("RecLong")
                        .HasColumnType("integer")
                        .HasColumnName("rec_long");

                    b.Property<int>("RecReceptions")
                        .HasColumnType("integer")
                        .HasColumnName("rec_receptions");

                    b.Property<int>("RecTargets")
                        .HasColumnType("integer")
                        .HasColumnName("rec_targets");

                    b.Property<int>("RecTd")
                        .HasColumnType("integer")
                        .HasColumnName("rec_td");

                    b.Property<int>("RecYds")
                        .HasColumnType("integer")
                        .HasColumnName("rec_yds");

                    b.Property<int>("RushAtt")
                        .HasColumnType("integer")
                        .HasColumnName("rush_att");

                    b.Property<double>("RushAvg")
                        .HasColumnType("double precision")
                        .HasColumnName("rush_avg");

                    b.Property<int>("RushFumbles")
                        .HasColumnType("integer")
                        .HasColumnName("rush_fumbles");

                    b.Property<int>("RushLong")
                        .HasColumnType("integer")
                        .HasColumnName("rush_long");

                    b.Property<int>("RushTd")
                        .HasColumnType("integer")
                        .HasColumnName("rush_td");

                    b.Property<int>("RushYds")
                        .HasColumnType("integer")
                        .HasColumnName("rush_yds");

                    b.Property<string>("SeasonType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("season_type");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("integer")
                        .HasColumnName("season_year");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<int>("XpAtt")
                        .HasColumnType("integer")
                        .HasColumnName("xp_att");

                    b.Property<int>("XpMade")
                        .HasColumnType("integer")
                        .HasColumnName("xp_made");

                    b.HasKey("Id")
                        .HasName("pk_team_season_stats");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_team_season_stats_team_id");

                    b.HasIndex("TeamId", "SeasonYear", "SeasonType")
                        .IsUnique()
                        .HasDatabaseName("ix_team_season_stats_team_id_season_year_season_type");

                    b.ToTable("team_season_stats", (string)null);
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Lat")
                        .HasColumnType("text")
                        .HasColumnName("lat");

                    b.Property<string>("Lng")
                        .HasColumnType("text")
                        .HasColumnName("lng");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RoofType")
                        .HasColumnType("text")
                        .HasColumnName("roof_type");

                    b.Property<string>("SrId")
                        .HasColumnType("text")
                        .HasColumnName("sr_id");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Surface")
                        .HasColumnType("text")
                        .HasColumnName("surface");

                    b.Property<string>("Zip")
                        .HasColumnType("text")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_venues");

                    b.HasIndex("SrId")
                        .IsUnique()
                        .HasDatabaseName("ix_venues_sr_id");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Coach", b =>
                {
                    b.HasOne("PatriotIndex.Domain.Entities.Team", "Team")
                        .WithMany("Coaches")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coaches_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.CoinToss", b =>
                {
                    b.HasOne("PatriotIndex.Domain.Entities.Period", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coin_tosses_periods_period_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coin_tosses_periods_period_id1");

                    b.HasOne("PatriotIndex.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coin_tosses_teams_winner_id");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Division", b =>
                {
                    b.HasOne("PatriotIndex.Domain.Entities.Conference", "Conference")
                        .WithMany("Divisions")
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_divisions_conferences_conference_id");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Drive", b =>
                {
                    b.HasOne("PatriotIndex.Domain.Entities.Team", "DefensiveTeam")
                        .WithMany()
                        .HasForeignKey("DefensiveTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_drives_teams_defensive_team_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Game", null)
                        .WithMany("Drives")
                        .HasForeignKey("GameId")
                        .HasConstraintName("fk_drives_games_game_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Team", "OffensiveTeam")
                        .WithMany()
                        .HasForeignKey("OffensiveTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_drives_teams_offensive_team_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Period", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_drives_periods_period_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Period", "Period")
                        .WithMany("Drives")
                        .HasForeignKey("PeriodId1")
                        .HasConstraintName("fk_drives_periods_period_id1");

                    b.Navigation("DefensiveTeam");

                    b.Navigation("OffensiveTeam");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.DriveEvent", b =>
                {
                    b.HasOne("PatriotIndex.Domain.Entities.Drive", "Drive")
                        .WithMany("Plays")
                        .HasForeignKey("DriveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pbp_drive_events_drives_drive_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("EndPossessionTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pbp_drive_events_teams_end_possession_team_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Team", "EndTeam")
                        .WithMany()
                        .HasForeignKey("EndTeamId")
                        .HasConstraintName("fk_pbp_drive_events_teams_end_team_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("StartPossessionTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pbp_drive_events_teams_start_possession_team_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Team", "StartTeam")
                        .WithMany()
                        .HasForeignKey("StartTeamId")
                        .HasConstraintName("fk_pbp_drive_events_teams_start_team_id");

                    b.Navigation("Drive");

                    b.Navigation("EndTeam");

                    b.Navigation("StartTeam");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Game", b =>
                {
                    b.HasOne("PatriotIndex.Domain.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_games_teams_away_team_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_games_teams_home_team_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_games_venues_venue_id");

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.PbpEventStatistics", b =>
                {
                    b.HasOne("PatriotIndex.Domain.Entities.DriveEvent", "DriveEvent")
                        .WithMany("EventStats")
                        .HasForeignKey("DriveEventId")
                        .HasConstraintName("fk_pbp_event_statistics_pbp_drive_events_drive_event_id");

                    b.HasOne("PatriotIndex.Domain.Entities.DriveEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pbp_event_statistics_pbp_drive_events_event_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("fk_pbp_event_statistics_players_player_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .HasConstraintName("fk_pbp_event_statistics_teams_team_id");

                    b.Navigation("DriveEvent");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Period", b =>
                {
                    b.HasOne("PatriotIndex.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_periods_games_game_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Game", "Game")
                        .WithMany("Periods")
                        .HasForeignKey("GameId1")
                        .HasConstraintName("fk_periods_games_game_id1");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Player", b =>
                {
                    b.HasOne("PatriotIndex.Domain.Entities.Team", "DraftTeam")
                        .WithMany()
                        .HasForeignKey("DraftTeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_players_teams_draft_team_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_players_teams_team_id");

                    b.Navigation("DraftTeam");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.PlayerGameStats", b =>
                {
                    b.HasOne("PatriotIndex.Domain.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_player_game_stats_games_game_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Player", "Player")
                        .WithMany("GameStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_game_stats_players_player_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_player_game_stats_teams_team_id");

                    b.Navigation("Game");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.PlayerSeasonStats", b =>
                {
                    b.HasOne("PatriotIndex.Domain.Entities.Player", "Player")
                        .WithMany("SeasonStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_season_stats_players_player_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_player_season_stats_teams_team_id");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Team", b =>
                {
                    b.HasOne("PatriotIndex.Domain.Entities.Division", "Division")
                        .WithMany("Teams")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_teams_divisions_division_id");

                    b.HasOne("PatriotIndex.Domain.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_teams_venues_venue_id");

                    b.OwnsOne("PatriotIndex.Domain.Entities.TeamColors", "Colors", b1 =>
                        {
                            b1.Property<Guid>("TeamId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Primary")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("primary_color");

                            b1.Property<string>("Secondary")
                                .HasColumnType("text")
                                .HasColumnName("secondary_color");

                            b1.HasKey("TeamId")
                                .HasName("pk_team_colors");

                            b1.ToTable("team_colors", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TeamId")
                                .HasConstraintName("fk_team_colors_teams_id");
                        });

                    b.Navigation("Colors");

                    b.Navigation("Division");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.TeamSeasonStats", b =>
                {
                    b.HasOne("PatriotIndex.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_season_stats_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Conference", b =>
                {
                    b.Navigation("Divisions");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Division", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Drive", b =>
                {
                    b.Navigation("Plays");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.DriveEvent", b =>
                {
                    b.Navigation("EventStats");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Game", b =>
                {
                    b.Navigation("Drives");

                    b.Navigation("Periods");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Period", b =>
                {
                    b.Navigation("Drives");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Player", b =>
                {
                    b.Navigation("GameStats");

                    b.Navigation("SeasonStats");
                });

            modelBuilder.Entity("PatriotIndex.Domain.Entities.Team", b =>
                {
                    b.Navigation("Coaches");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
