using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PatriotIndex.Domain.Migrations
{
    /// <inheritdoc />
    public partial class khgkhvkhv : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "play_statistics",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    play_id = table.Column<Guid>(type: "uuid", nullable: false),
                    player_id = table.Column<string>(type: "text", nullable: true),
                    player_name = table.Column<string>(type: "text", nullable: true),
                    player_jersey = table.Column<string>(type: "text", nullable: true),
                    player_position = table.Column<string>(type: "text", nullable: true),
                    player_sr_id = table.Column<string>(type: "text", nullable: true),
                    team_id = table.Column<string>(type: "text", nullable: true),
                    team_name = table.Column<string>(type: "text", nullable: true),
                    team_market = table.Column<string>(type: "text", nullable: true),
                    team_alias = table.Column<string>(type: "text", nullable: true),
                    team_sr_id = table.Column<string>(type: "text", nullable: true),
                    stat_type = table.Column<string>(type: "character varying(21)", maxLength: 21, nullable: false),
                    block_play_stat_category = table.Column<string>(type: "text", nullable: true),
                    blocks = table.Column<int>(type: "integer", nullable: true),
                    conversion_play_stat_category = table.Column<string>(type: "text", nullable: true),
                    conversion_play_stat_attempt = table.Column<int>(type: "integer", nullable: true),
                    conversion_play_stat_complete = table.Column<int>(type: "integer", nullable: true),
                    conversion_play_stat_safety = table.Column<int>(type: "integer", nullable: true),
                    defense_conversion_play_stat_category = table.Column<string>(type: "text", nullable: true),
                    defense_conversion_play_stat_attempt = table.Column<int>(type: "integer", nullable: true),
                    defense_conversion_play_stat_complete = table.Column<int>(type: "integer", nullable: true),
                    defense_play_stat_category = table.Column<string>(type: "text", nullable: true),
                    primary = table.Column<int>(type: "integer", nullable: true),
                    tackle = table.Column<int>(type: "integer", nullable: true),
                    assist = table.Column<int>(type: "integer", nullable: true),
                    assisted_tackle = table.Column<int>(type: "integer", nullable: true),
                    tackle_for_loss = table.Column<double>(type: "double precision", nullable: true),
                    tackle_for_loss_yards = table.Column<double>(type: "double precision", nullable: true),
                    assisted_tackle_for_loss = table.Column<double>(type: "double precision", nullable: true),
                    missed_tackle = table.Column<int>(type: "integer", nullable: true),
                    defense_play_stat_sack = table.Column<double>(type: "double precision", nullable: true),
                    defense_play_stat_sack_yards = table.Column<double>(type: "double precision", nullable: true),
                    assisted_sack = table.Column<double>(type: "double precision", nullable: true),
                    qb_hit = table.Column<int>(type: "integer", nullable: true),
                    defense_play_stat_hurry = table.Column<int>(type: "integer", nullable: true),
                    defense_play_stat_knockdown = table.Column<int>(type: "integer", nullable: true),
                    defense_play_stat_blitz = table.Column<int>(type: "integer", nullable: true),
                    interception = table.Column<int>(type: "integer", nullable: true),
                    interception_yards = table.Column<int>(type: "integer", nullable: true),
                    interception_touchdowns = table.Column<int>(type: "integer", nullable: true),
                    pass_defended = table.Column<int>(type: "integer", nullable: true),
                    batted_pass = table.Column<int>(type: "integer", nullable: true),
                    def_target = table.Column<int>(type: "integer", nullable: true),
                    def_comp = table.Column<int>(type: "integer", nullable: true),
                    forced_fumble = table.Column<int>(type: "integer", nullable: true),
                    fumble_recovery = table.Column<int>(type: "integer", nullable: true),
                    defense_play_stat_safety = table.Column<int>(type: "integer", nullable: true),
                    sp_tackle = table.Column<int>(type: "integer", nullable: true),
                    sp_assist = table.Column<int>(type: "integer", nullable: true),
                    sp_forced_fumble = table.Column<int>(type: "integer", nullable: true),
                    sp_fumble_recovery = table.Column<int>(type: "integer", nullable: true),
                    sp_block = table.Column<int>(type: "integer", nullable: true),
                    misc_tackle = table.Column<int>(type: "integer", nullable: true),
                    misc_assist = table.Column<int>(type: "integer", nullable: true),
                    misc_forced_fumble = table.Column<int>(type: "integer", nullable: true),
                    misc_fumble_recovery = table.Column<int>(type: "integer", nullable: true),
                    defense_play_stat_nullified = table.Column<int>(type: "integer", nullable: true),
                    down = table.Column<int>(type: "integer", nullable: true),
                    down_conversion_play_stat_attempt = table.Column<int>(type: "integer", nullable: true),
                    down_conversion_play_stat_complete = table.Column<int>(type: "integer", nullable: true),
                    extra_point_play_stat_attempt = table.Column<int>(type: "integer", nullable: true),
                    extra_point_play_stat_made = table.Column<int>(type: "integer", nullable: true),
                    extra_point_play_stat_missed = table.Column<int>(type: "integer", nullable: true),
                    extra_point_play_stat_blocked = table.Column<int>(type: "integer", nullable: true),
                    aborted = table.Column<int>(type: "integer", nullable: true),
                    extra_point_play_stat_returned = table.Column<int>(type: "integer", nullable: true),
                    extra_point_play_stat_safety = table.Column<int>(type: "integer", nullable: true),
                    field_goal_play_stat_attempt = table.Column<int>(type: "integer", nullable: true),
                    field_goal_play_stat_attempt_yards = table.Column<int>(type: "integer", nullable: true),
                    made = table.Column<int>(type: "integer", nullable: true),
                    missed = table.Column<int>(type: "integer", nullable: true),
                    blocked = table.Column<int>(type: "integer", nullable: true),
                    field_goal_play_stat_yards = table.Column<int>(type: "integer", nullable: true),
                    field_goal_play_stat_inside20 = table.Column<int>(type: "integer", nullable: true),
                    field_goal_play_stat_returned = table.Column<int>(type: "integer", nullable: true),
                    field_goal_play_stat_nullified = table.Column<int>(type: "integer", nullable: true),
                    category = table.Column<string>(type: "text", nullable: true),
                    rush = table.Column<int>(type: "integer", nullable: true),
                    pass = table.Column<int>(type: "integer", nullable: true),
                    penalty = table.Column<int>(type: "integer", nullable: true),
                    total = table.Column<int>(type: "integer", nullable: true),
                    play_category = table.Column<string>(type: "text", nullable: true),
                    fumbles = table.Column<int>(type: "integer", nullable: true),
                    lost_fumbles = table.Column<int>(type: "integer", nullable: true),
                    own_recoveries = table.Column<int>(type: "integer", nullable: true),
                    own_recovery_yards = table.Column<int>(type: "integer", nullable: true),
                    opp_recoveries = table.Column<int>(type: "integer", nullable: true),
                    opp_recovery_yards = table.Column<int>(type: "integer", nullable: true),
                    fumble_play_stat_out_of_bounds = table.Column<int>(type: "integer", nullable: true),
                    forced_fumbles = table.Column<int>(type: "integer", nullable: true),
                    own_recovery_tds = table.Column<int>(type: "integer", nullable: true),
                    opp_recovery_tds = table.Column<int>(type: "integer", nullable: true),
                    end_zone_recovery_tds = table.Column<int>(type: "integer", nullable: true),
                    fumble_play_stat_nullified = table.Column<int>(type: "integer", nullable: true),
                    int_return_play_stat_yards = table.Column<int>(type: "integer", nullable: true),
                    int_return_play_stat_touchdowns = table.Column<int>(type: "integer", nullable: true),
                    longest = table.Column<int>(type: "integer", nullable: true),
                    int_return_play_stat_returns = table.Column<int>(type: "integer", nullable: true),
                    kick_play_stat_attempt = table.Column<int>(type: "integer", nullable: true),
                    kick_play_stat_yards = table.Column<int>(type: "integer", nullable: true),
                    kick_play_stat_net_yards = table.Column<int>(type: "integer", nullable: true),
                    touchback = table.Column<int>(type: "integer", nullable: true),
                    onside_attempt = table.Column<int>(type: "integer", nullable: true),
                    onside_success = table.Column<int>(type: "integer", nullable: true),
                    squib_kick = table.Column<int>(type: "integer", nullable: true),
                    endzone = table.Column<int>(type: "integer", nullable: true),
                    kick_play_stat_inside20 = table.Column<int>(type: "integer", nullable: true),
                    returned = table.Column<int>(type: "integer", nullable: true),
                    out_of_bounds = table.Column<int>(type: "integer", nullable: true),
                    own_recovery = table.Column<int>(type: "integer", nullable: true),
                    own_recovery_touchdown = table.Column<int>(type: "integer", nullable: true),
                    kick_play_stat_nullified = table.Column<int>(type: "integer", nullable: true),
                    misc_return_play_stat_yards = table.Column<int>(type: "integer", nullable: true),
                    misc_return_play_stat_touchdowns = table.Column<int>(type: "integer", nullable: true),
                    blk_fg_touchdowns = table.Column<int>(type: "integer", nullable: true),
                    blk_punt_touchdowns = table.Column<int>(type: "integer", nullable: true),
                    fg_return_touchdowns = table.Column<int>(type: "integer", nullable: true),
                    ez_rec_touchdowns = table.Column<int>(type: "integer", nullable: true),
                    returns = table.Column<int>(type: "integer", nullable: true),
                    longest_touchdown = table.Column<int>(type: "integer", nullable: true),
                    attempt = table.Column<int>(type: "integer", nullable: true),
                    attempt_yards = table.Column<int>(type: "integer", nullable: true),
                    complete = table.Column<int>(type: "integer", nullable: true),
                    pass_play_stat_yards = table.Column<int>(type: "integer", nullable: true),
                    touchdowns = table.Column<int>(type: "integer", nullable: true),
                    interceptions = table.Column<int>(type: "integer", nullable: true),
                    int_touchdowns = table.Column<int>(type: "integer", nullable: true),
                    pass_play_stat_first_down = table.Column<int>(type: "integer", nullable: true),
                    air_yards = table.Column<int>(type: "integer", nullable: true),
                    sack = table.Column<int>(type: "integer", nullable: true),
                    sack_yards = table.Column<int>(type: "integer", nullable: true),
                    spike = table.Column<int>(type: "integer", nullable: true),
                    throw_away = table.Column<int>(type: "integer", nullable: true),
                    poor_throw = table.Column<int>(type: "integer", nullable: true),
                    defended = table.Column<int>(type: "integer", nullable: true),
                    dropped = table.Column<int>(type: "integer", nullable: true),
                    batted = table.Column<int>(type: "integer", nullable: true),
                    on_target = table.Column<int>(type: "integer", nullable: true),
                    blitz = table.Column<int>(type: "integer", nullable: true),
                    hurry = table.Column<int>(type: "integer", nullable: true),
                    knockdown = table.Column<int>(type: "integer", nullable: true),
                    pocket_time = table.Column<double>(type: "double precision", nullable: true),
                    gross_yards = table.Column<int>(type: "integer", nullable: true),
                    net_yards = table.Column<int>(type: "integer", nullable: true),
                    inside20 = table.Column<int>(type: "integer", nullable: true),
                    goal_to_go = table.Column<int>(type: "integer", nullable: true),
                    incompletion_type = table.Column<string>(type: "text", nullable: true),
                    nullified = table.Column<int>(type: "integer", nullable: true),
                    safety = table.Column<int>(type: "integer", nullable: true),
                    penalties = table.Column<int>(type: "integer", nullable: true),
                    yards = table.Column<int>(type: "integer", nullable: true),
                    first_down = table.Column<int>(type: "integer", nullable: true),
                    no_play = table.Column<int>(type: "integer", nullable: true),
                    penalty_type = table.Column<string>(type: "text", nullable: true),
                    declined = table.Column<int>(type: "integer", nullable: true),
                    offsetting = table.Column<int>(type: "integer", nullable: true),
                    punt_play_stat_attempt = table.Column<int>(type: "integer", nullable: true),
                    punt_play_stat_yards = table.Column<int>(type: "integer", nullable: true),
                    punt_play_stat_net_yards = table.Column<int>(type: "integer", nullable: true),
                    punt_play_stat_touchback = table.Column<int>(type: "integer", nullable: true),
                    punt_play_stat_inside20 = table.Column<int>(type: "integer", nullable: true),
                    punt_play_stat_blocked = table.Column<int>(type: "integer", nullable: true),
                    hang_time = table.Column<double>(type: "double precision", nullable: true),
                    return_yards = table.Column<int>(type: "integer", nullable: true),
                    fair_catch = table.Column<int>(type: "integer", nullable: true),
                    downed = table.Column<int>(type: "integer", nullable: true),
                    end_zone = table.Column<int>(type: "integer", nullable: true),
                    punt_play_stat_nullified = table.Column<int>(type: "integer", nullable: true),
                    target = table.Column<int>(type: "integer", nullable: true),
                    reception = table.Column<int>(type: "integer", nullable: true),
                    receive_play_stat_yards = table.Column<int>(type: "integer", nullable: true),
                    receive_play_stat_touchdowns = table.Column<int>(type: "integer", nullable: true),
                    receive_play_stat_first_down = table.Column<int>(type: "integer", nullable: true),
                    receive_play_stat_air_yards = table.Column<int>(type: "integer", nullable: true),
                    yards_after_catch = table.Column<int>(type: "integer", nullable: true),
                    yards_after_contact = table.Column<int>(type: "integer", nullable: true),
                    broken_tackles = table.Column<int>(type: "integer", nullable: true),
                    receive_play_stat_dropped = table.Column<int>(type: "integer", nullable: true),
                    catchable = table.Column<int>(type: "integer", nullable: true),
                    redzone_target = table.Column<int>(type: "integer", nullable: true),
                    receive_play_stat_inside20 = table.Column<int>(type: "integer", nullable: true),
                    receive_play_stat_goal_to_go = table.Column<int>(type: "integer", nullable: true),
                    receive_play_stat_nullified = table.Column<int>(type: "integer", nullable: true),
                    receive_play_stat_safety = table.Column<int>(type: "integer", nullable: true),
                    return_play_stat_category = table.Column<string>(type: "text", nullable: true),
                    return_play_stat_play_category = table.Column<string>(type: "text", nullable: true),
                    return_play_stat_yards = table.Column<int>(type: "integer", nullable: true),
                    return_play_stat_touchdowns = table.Column<int>(type: "integer", nullable: true),
                    return_play_stat_touchback = table.Column<int>(type: "integer", nullable: true),
                    return_play_stat_fair_catch = table.Column<int>(type: "integer", nullable: true),
                    return_play_stat_first_down = table.Column<int>(type: "integer", nullable: true),
                    return_play_stat_longest = table.Column<int>(type: "integer", nullable: true),
                    return_play_stat_downed = table.Column<int>(type: "integer", nullable: true),
                    return_play_stat_out_of_bounds = table.Column<int>(type: "integer", nullable: true),
                    lateral = table.Column<int>(type: "integer", nullable: true),
                    return_play_stat_nullified = table.Column<int>(type: "integer", nullable: true),
                    rush_play_stat_attempt = table.Column<int>(type: "integer", nullable: true),
                    rush_play_stat_yards = table.Column<int>(type: "integer", nullable: true),
                    rush_play_stat_touchdowns = table.Column<int>(type: "integer", nullable: true),
                    rush_play_stat_first_down = table.Column<int>(type: "integer", nullable: true),
                    rush_play_stat_tackle_for_loss = table.Column<int>(type: "integer", nullable: true),
                    rush_play_stat_tackle_for_loss_yards = table.Column<int>(type: "integer", nullable: true),
                    rush_play_stat_broken_tackles = table.Column<int>(type: "integer", nullable: true),
                    scramble = table.Column<int>(type: "integer", nullable: true),
                    kneel_down = table.Column<int>(type: "integer", nullable: true),
                    rush_play_stat_yards_after_contact = table.Column<int>(type: "integer", nullable: true),
                    rush_play_stat_inside20 = table.Column<int>(type: "integer", nullable: true),
                    rush_play_stat_goal_to_go = table.Column<int>(type: "integer", nullable: true),
                    rush_play_stat_lateral = table.Column<int>(type: "integer", nullable: true),
                    rush_play_stat_nullified = table.Column<int>(type: "integer", nullable: true),
                    rush_play_stat_safety = table.Column<int>(type: "integer", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_play_statistics", x => x.id);
                    table.ForeignKey(
                        name: "fk_play_statistics_pbp_drive_events_play_id",
                        column: x => x.play_id,
                        principalTable: "pbp_drive_events",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_play_statistics_play_id_stat_type",
                table: "play_statistics",
                columns: new[] { "play_id", "stat_type" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "play_statistics");
        }
    }
}
