using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PatriotIndex.Domain.Migrations
{
    /// <inheritdoc />
    public partial class klefwkmwlfkenmkjnvskljdrf : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE sync_logs DROP CONSTRAINT IF EXISTS sync_logs_pkey;");
            migrationBuilder.Sql("ALTER TABLE sync_logs DROP COLUMN id;");
            migrationBuilder.Sql("ALTER TABLE sync_logs ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE sync_logs DROP CONSTRAINT IF EXISTS sync_logs_pkey;");
            migrationBuilder.Sql("ALTER TABLE sync_logs DROP COLUMN id;");
            migrationBuilder.Sql("ALTER TABLE sync_logs ADD COLUMN id UUID DEFAULT gen_random_uuid() PRIMARY KEY;");
        }
    }
}
